###
POST http://localhost:8080/api/socks?color=RED&size=M&cottonPart=40&quantity=5

###
POST http://localhost:8080/api/socks?color=RED&size=M&cottonPart=5&quantity=10

###
POST http://localhost:8080/api/socks?color=RED&size=M&cottonPart=95&quantity=20

###
PUT http://localhost:8080/api/socks?color=RED&size=M&cottonPart=40&quantity=5

###
GET http://localhost:8080/api/socks?color=RED&size=M&cottonMin=90

###
GET http://localhost:8080/api/socks?color=RED&size=M&cottonMax=10

###
DELETE http://localhost:8080/api/socks?color=RED&size=M&cottonPart=40&quantity=5
