###
POST http://localhost:8080/api/socks?color=RED&size=36&cottonPart=40&quantity=5

###
POST http://localhost:8080/api/socks?color=RED&size=36&cottonPart=5&quantity=10

###
POST http://localhost:8080/api/socks?color=RED&size=36&cottonPart=95&quantity=20

###
PUT http://localhost:8080/api/socks?color=RED&size=36&cottonPart=40&quantity=5

###
GET http://localhost:8080/api/socks?color=RED&size=36&cottonMin=40

###
GET http://localhost:8080/api/socks?color=RED&size=36&cottonMax=40

###
DELETE http://localhost:8080/api/socks?color=RED&size=36&cottonPart=40&quantity=5
