POST http://localhost:8080/socks/add
Content-Type: application/json

{
  "color": "BLUE",
  "size": "L",
  "composition": "COTTON_30",
  "quantity": 35
}

###
POST http://localhost:8080/socks/add
Content-Type: application/json

{
  "color": "BLUE",
  "size": "L",
  "composition": "COTTON_30",
  "quantity": 30
}

###
POST http://localhost:8080/socks/add
Content-Type: application/json

{
  "color": "BLUE",
  "size": "XL",
  "composition": "COTTON_60",
  "quantity": 20
}

###
GET http://localhost:8080/socks/color
Content-Type: application/json

{
  "color": "BLUE",
  "size": "L",
  "composition": "COTTON_30",
  "quantity": 0
}

###
GET http://localhost:8080/socks/color
Content-Type: application/json

{
"BLUE": "BLUE"
}
